version: "3.9"
services:
  web:
    build: .
    expose:
      - 8000
    command: >
      bash -c "python manage.py makemigrations --noinput && 
               python manage.py migrate --noinput && 
               python manage.py collectstatic --noinput && 
               gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 4"
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
      - media_volume:/code/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
